name: Remove old artifacts

on:
  workflow_dispatch:
  schedule:
    # Every Sunday at 1am
    - cron: '0 1 * * 0'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@44fc7acaf1b3d0987da0e8d4707a989d80e9554b # v1
        with:
          age: '3 days' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
          # Optional inputs
          skip-tags: true
          # skip-recent: 5
