name: test-macos
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test-macos:
    runs-on: 
      - self-hosted
      - ${{ matrix.os }}
      - ${{ matrix.architecture }}
      - sp53
    strategy:
      matrix: 
        node: 
          - 14
          - 16
          - lts/*
        architecture:
          - x64
        os:
          - macos

    steps:
    - uses: actions/checkout@v2

    - name: Debugging 1
      run: pwd && ls -la
      working-directory: src

    - name: Setup node
      uses: actions/setup-node@v2
      with: 
        node-version: ${{ matrix.node }}

    - name: Install modules
      run: npm install
      working-directory: src

    - name: Make sure Jest is installed
      run: npm install jest

    - name: Debugging 2
      run: pwd && ls -la
      working-directory: src
      
    - name: Run tests
      run: npm run test
      working-directory: src
      env:
        BSI_CONTENT_LIBRARY: 'abc 123'
        BSI_HOST: ${{ secrets.BSI_HOST }}
        BSI_PREFIX: ${{ secrets.BSI_PREFIX }}
        BSI_APP_ID: 'a3e0f5d2-000a-464f-998d-33d333b175d7'
        BSI_LOGON_USER_DIR: ${{ secrets.BSI_LOGON_USER_DIR }}
        BSI_LOGON_USER_ID: ${{ secrets.BSI_LOGON_USER_ID }}
        BSI_LOGON_PWD: ${{ secrets.BSI_LOGON_PWD }}
        BSI_TEST_TIMEOUT: 120000
        BSI_CERT_FILE: ${{ secrets.BSI_MAC_CERT_FILE }}
        BSI_CERT_KEY_FILE: ${{ secrets.BSI_MAC_CERT_KEY_FILE }}

    - name: Send job status to MQTT when done
      uses: potaesm/github-actions-mqtt-request@1.0.0
      if: always()
      env:
        JOB_STATUS: ${{ job.status }}
        NODE_VERSION: ${{ matrix.node }}
      with:
        url: mqtt://192.168.100.20:1884
        topic: control/sp53/mac-build1/action-runner
        payload: '{ "type":"ci-test", "repo": "${{ github.repository }}", "job": "${{ github.job }}", "workflow": "${{ github.workflow }}", "nodeVersion": "${{ env.NODE_VERSION }}","conclusion":"${{ env.JOB_STATUS }}" }'
        connectTimeout: 30000
        
